# Lab 1: Pandas Fundamentals

## Objective

This lab demonstrates fundamental Pandas operations used for working with tabular datasets.

The **WineQT.csv** dataset is used to practice loading, inspecting, selecting, filtering, transforming, grouping, aggregating, and merging data.

---

## Tasks Covered

- Loading CSV data into a Pandas DataFrame
- Inspecting dataset structure and statistics
- Selecting rows and columns
- Filtering data using Boolean conditions
- Creating derived columns
- Grouping and aggregation
- Merging DataFrames

---

## Libraries Used

```python
import pandas as pd
import numpy as np

```
### Pandas – Used for data manipulation and analysis.
### NumPy – Used for numerical operations.

### Task 1: Load a CSV into a DataFrame and Inspect Datase

**Step 1.1: Import Libraries**

In [1]:
import pandas as pd
import numpy as np

**Step 1.2: Load Dataset**

In [2]:
df = pd.read_csv("WineQT.csv")

**Step 1.3: Preview Dataset**

In [ ]:
The head() function displays the first five rows of the DataFrame.

In [3]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,3
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,4

***Step 1.4: Dataset Information***

Checks dataset structure, data types, and missing values.

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64
 12  Id                    1143 non-null   int64
dtypes: float64(11), int64(2)
memory usage: 116.2 KB

***Step 1.5: Statistical Summary***

`describe()` computes count, mean, standard deviation, and quartiles for every numeric column in one call.

In [5]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
count,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000
mean,8.311111,0.531339,0.268364,2.532152,0.086933,15.615486,45.914698,0.996730,3.311015,0.657708,10.442111,5.657043,804.969379
std,1.747595,0.179633,0.196686,1.355917,0.047267,10.250486,32.782130,0.001925,0.156664,0.170399,1.082196,0.805824,463.997116
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000,0.000000
25%,7.100000,0.392500,0.090000,1.900000,0.070000,7.000000,21.000000,0.995570,3.205000,0.550000,9.500000,5.000000,411.000000
50%,7.900000,0.520000,0.250000,2.200000,0.079000,13.000000,37.000000,0.996680,3.310000,0.620000,10.200000,6.000000,794.000000
75%,9.100000,0.640000,0.420000,2.600000,0.090000,21.000000,61.000000,0.997845,3.400000,0.730000,11.100000,6.000000,1209.500000
max,15.900000,1.580000,1.000000,15.500000,0.611000,68.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000,1597.000000

***Step 1.6: Check Dataset Dimensions***

`shape` returns a `(rows, columns)` tuple.

In [8]:
df.shape

(1143, 13)


## Task 2: Selecting Rows and Columns

***Step 2.1: Select Columns***

Pull out a single column or a subset of columns for targeted analysis.

In [9]:
df["alcohol"]

0        9.4
1        9.8
2        9.8
3        9.8
4        9.4
        ...
1138    11.0
1139     9.5
1140    10.5
1141    11.2
1142    10.2
Name: alcohol, Length: 1143, dtype: float64

In [10]:
df[["alcohol", "quality"]]

      alcohol  quality
0         9.4        5
1         9.8        5
2         9.8        5
3         9.8        6
4         9.4        5
...       ...      ...
1138     11.0        6
1139      9.5        6
1140     10.5        5
1141     11.2        6
1142     10.2        5

[1143 rows x 2 columns]

***Step 2.2: Select Rows with `loc[]`***

`loc[]` selects rows and columns by their labels rather than their positions.

In [11]:
df.loc[0]

fixed acidity            7.4000
volatile acidity         0.7000
citric acid              0.0000
residual sugar           1.9000
chlorides                0.0760
free sulfur dioxide     11.0000
total sulfur dioxide    34.0000
density                  0.9978
pH                       3.5100
sulphates                0.5600
alcohol                  9.4000
quality                  5.0000
Id                       0.0000
Name: 0, dtype: float64

In [14]:
df.loc[0:5, ["alcohol", "quality"]]

   alcohol  quality
0      9.4        5
1      9.8        5
2      9.8        5
3      9.8        6
4      9.4        5
5      9.4        5

***Step 2.3: Select Rows with `iloc[]`***

`iloc[]` does the same job as `loc[]`, but works off integer positions instead of labels.

In [15]:
df.iloc[0]

fixed acidity            7.4000
volatile acidity         0.7000
citric acid              0.0000
residual sugar           1.9000
chlorides                0.0760
free sulfur dioxide     11.0000
total sulfur dioxide    34.0000
density                  0.9978
pH                       3.5100
sulphates                0.5600
alcohol                  9.4000
quality                  5.0000
Id                       0.0000
Name: 0, dtype: float64

In [17]:
df.iloc[0:6, [11, 12]]

   quality  Id
0        5   0
1        5   1
2        5   2
3        6   3
4        5   4
5        5   5

***Step 2.4: Filter Rows with Boolean Conditions***

Apply a condition to a column and use it as a mask to keep only the matching rows.

In [19]:
df[df["quality"] > 7]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
190,7.9,0.35,0.46,3.6,0.078,15.0,37.0,0.99730,3.35,0.86,12.8,8,267
197,10.3,0.32,0.45,6.4,0.073,5.0,13.0,0.99760,3.23,0.82,12.6,8,278
271,5.6,0.85,0.05,1.4,0.045,12.0,88.0,0.99240,3.56,0.82,12.9,8,390
310,12.6,0.31,0.72,2.2,0.072,6.0,29.0,0.99870,2.88,0.82,9.8,8,440
321,11.3,0.62,0.67,5.2,0.086,6.0,19.0,0.99880,3.22,0.69,13.4,8,455
340,9.4,0.30,0.56,2.8,0.080,6.0,17.0,0.99640,3.15,0.92,11.7,8,481
349,10.7,0.35,0.53,2.6,0.070,5.0,16.0,0.99720,3.15,0.65,11.0,8,495
352,10.7,0.35,0.53,2.6,0.070,5.0,16.0,0.99720,3.15,0.65,11.0,8,498
419,5.0,0.42,0.24,2.0,0.060,19.0,50.0,0.99170,3.72,0.74,14.0,8,588
747,9.1,0.40,0.50,1.8,0.071,7.0,16.0,0.99462,3.21,0.69,12.5,8,1061
769,10.0,0.26,0.54,1.9,0.083,42.0,74.0,0.99451,2.98,0.63,11.8,8,1090
793,7.9,0.54,0.34,2.5,0.076,8.0,17.0,0.99235,3.20,0.72,13.1,8,1120
850,8.6,0.42,0.39,1.8,0.068,6.0,12.0,0.99516,3.35,0.69,11.7,8,1202
996,7.2,0.33,0.33,1.7,0.061,3.0,13.0,0.99600,3.23,1.10,10.0,8,1403
1030,7.2,0.38,0.31,2.0,0.056,15.0,29.0,0.99472,3.23,0.76,11.3,8,1449
1104,7.4,0.36,0.30,1.8,0.074,17.0,24.0,0.99419,3.24,0.70,11.4,8,1549

In [20]:
df[df["alcohol"] > 12]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
32,4.6,0.52,0.15,2.1,0.054,8.0,65.0,0.99340,3.90,0.56,13.100000,4,45
91,5.6,0.50,0.09,2.3,0.049,17.0,99.0,0.99370,3.63,0.63,13.000000,5,131
96,5.2,0.34,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.000000,6,142
98,5.2,0.34,0.00,1.8,0.050,27.0,63.0,0.99160,3.68,0.79,14.000000,6,144
148,9.7,0.53,0.60,2.0,0.039,5.0,19.0,0.99585,3.30,0.86,12.400000,6,210
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1052,5.3,0.47,0.11,2.2,0.048,16.0,89.0,0.99182,3.54,0.88,13.566667,7,1475
1054,5.3,0.47,0.11,2.2,0.048,16.0,89.0,0.99182,3.54,0.88,13.600000,7,1477
1064,7.1,0.22,0.49,1.8,0.039,8.0,18.0,0.99344,3.39,0.56,12.400000,6,1490
1122,6.4,0.36,0.53,2.2,0.230,19.0,35.0,0.99340,3.37,0.93,12.400000,6,1570
1125,6.0,0.58,0.20,2.4,0.075,15.0,50.0,0.99467,3.58,0.67,12.500000,6,1573


### Task 3: Create a New Column

***Step 3.1: Derive a Boolean Column***

Build a new column that flags whether alcohol content crosses a threshold.

In [31]:
df["alcohol_level"] = df["alcohol"] > 15

In [32]:
df[["alcohol", "alcohol_level"]].head()

   alcohol  alcohol_level
0      9.4           True
1      9.8           True
2      9.8           True
3      9.8           True
4      9.4           True

***Step 3.2: Derive a Numeric Column***

Compute a ratio column by dividing one numeric column by another.

In [33]:
df["acidity_ratio"] = df["fixed acidity"] / df["volatile acidity"]

In [34]:
df[["fixed acidity", "volatile acidity", "acidity_ratio"]].head()

   fixed acidity  volatile acidity  acidity_ratio
0            7.4              0.70      10.571429
1            7.8              0.88       8.863636
2            7.8              0.76      10.263158
3           11.2              0.28      40.000000
4            7.4              0.70      10.571429

### Why No Loop?

You might think we need:

***for row in df:***
    ...

    But we don't.

Pandas performs the operation across the entire column:

***df["fixed acidity"] / df["volatile acidity"]***
    
This is vectorized computation.

This concept becomes especially important in my NumPy lab.

### Task 4: Group By and Aggregate

***Step 4.1: Group by Quality***

Group rows by the `quality` category to prepare for per-group calculations.

In [35]:
df.groupby("quality")

***Step 4.2: Aggregate Mean and Count***

For each quality group, compute the average alcohol content and how many rows fall into it.

In [36]:
df.groupby("quality")["alcohol"].agg(["mean", "count"])

              mean  count
quality
3         9.691667      6
4        10.260606     33
5         9.902277    483
6        10.655339    462
7        11.482634    143
8        11.937500     16

### Task 5: Merge DataFrames

***Step 5.1: Build Two Sample DataFrames***

Set up two small DataFrames that share an `Id` column, so they can be joined together.

In [37]:
df1 = pd.DataFrame({
    "Id": [1, 2, 3, 4],
    "quality": [5, 6, 7, 8]
})

df2 = pd.DataFrame({
    "Id": [1, 2, 3, 4],
    "category": ["Low", "Medium", "Good", "Excellent"]
})

***Step 5.2: Merge on the Shared Key***

Join the two DataFrames on `Id` to combine their columns into one table

In [39]:
merged_df = pd.merge(df1, df2, on="Id")
merged_df

   Id  quality   category
0   1        5        Low
1   2        6     Medium
2   3        7       Good
3   4        8  Excellent

***Step 5.3: Check the Row Count***

Confirm the merge produced the expected number of rows.

In [41]:
merged_df.shape[0]

4


## Overall Observations

- Pandas makes it straightforward to load, inspect, and manipulate tabular data with just a few method calls.
- Functions like `head()`, `info()`, `describe()`, and `shape` give a fast first impression of a dataset's size, types, and spread.
- Rows and columns can be accessed through plain indexing, `loc[]` for label-based selection, or `iloc[]` for position-based selection.
- Boolean masks make it easy to isolate rows that meet a specific condition.
- New columns can be built on the fly from existing ones, whether as flags or calculated ratios.
- `groupby()` combined with `agg()` is a compact way to summarize data across categories.
- `merge()` lets separate DataFrames be stitched together using a common key column.